# Generated by Django 5.2.7 on 2025-10-14 21:57

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banco', '0001_initial'),
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentaahorro',
            name='actualizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_actualizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuentaahorro',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cuentaahorro',
            name='estado',
            field=models.ForeignKey(limit_choices_to={'dominio': 'CUENTA_AHORRO'}, on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_ahorro', to='core.catestado'),
        ),
        migrations.AddField(
            model_name='cuentaahorro',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuentas_ahorro', to='core.socio'),
        ),
        migrations.AddField(
            model_name='dividendo',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividendos', to='core.socio'),
        ),
        migrations.AddField(
            model_name='fondomutuo',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fondos_cerrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fondomutuo',
            name='estado',
            field=models.ForeignKey(help_text='ABIERTO/CERRADO', limit_choices_to={'dominio': 'FONDO_MUTUO'}, on_delete=django.db.models.deletion.PROTECT, related_name='fondos_mutuos', to='core.catestado'),
        ),
        migrations.AddField(
            model_name='garante',
            name='socio_garante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_garantizados', to='core.socio'),
        ),
        migrations.AddField(
            model_name='movimientofondomutuo',
            name='fondo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='banco.fondomutuo'),
        ),
        migrations.AddField(
            model_name='movimientofondomutuo',
            name='realizado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_fondo_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movimientofondomutuo',
            name='socio',
            field=models.ForeignKey(blank=True, help_text='Socio que realiza el aporte o recibe la ayuda', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_fondo', to='core.socio'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='estado',
            field=models.ForeignKey(blank=True, limit_choices_to={'dominio': 'NOTIFICACION'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notificaciones', to='core.catestado'),
        ),
        migrations.AddField(
            model_name='notificacion',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.socio'),
        ),
        migrations.AddField(
            model_name='pagoprestamo',
            name='cuota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='banco.cuotaprestamo'),
        ),
        migrations.AddField(
            model_name='pagoprestamo',
            name='realizado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_prestamos_procesados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='periododividendo',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='periodos_cerrados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dividendo',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dividendos', to='banco.periododividendo'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='aprobado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='prestamos_aprobados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prestamos', to='core.socio'),
        ),
        migrations.AddField(
            model_name='pagoprestamo',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos', to='banco.prestamo'),
        ),
        migrations.AddField(
            model_name='garante',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='garantes', to='banco.prestamo'),
        ),
        migrations.AddField(
            model_name='cuotaprestamo',
            name='prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas', to='banco.prestamo'),
        ),
        migrations.AddField(
            model_name='solicitudayudamutua',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_ayuda_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudayudamutua',
            name='fondo',
            field=models.ForeignKey(help_text='Fondo del período en que se solicita', on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes', to='banco.fondomutuo'),
        ),
        migrations.AddField(
            model_name='solicitudayudamutua',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_revisadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='solicitudayudamutua',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='solicitudes_ayuda', to='core.socio'),
        ),
        migrations.AddField(
            model_name='movimientofondomutuo',
            name='solicitud_ayuda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='banco.solicitudayudamutua'),
        ),
        migrations.AddIndex(
            model_name='tipocuenta',
            index=models.Index(fields=['codigo'], name='TIPO_CUENTA_codigo_212530_idx'),
        ),
        migrations.AddIndex(
            model_name='tipocuenta',
            index=models.Index(fields=['activo'], name='TIPO_CUENTA_activo_a25fe1_idx'),
        ),
        migrations.AddConstraint(
            model_name='tipocuenta',
            constraint=models.CheckConstraint(condition=models.Q(('tasa_interes_anual__gte', 0)), name='chk_tipo_cuenta_tasa_positiva'),
        ),
        migrations.AddConstraint(
            model_name='tipocuenta',
            constraint=models.CheckConstraint(condition=models.Q(('monto_minimo__gte', 0)), name='chk_tipo_cuenta_monto_minimo_positivo'),
        ),
        migrations.AddField(
            model_name='cuentaahorro',
            name='tipo_cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banco.tipocuenta'),
        ),
        migrations.AddIndex(
            model_name='tipoprestamo',
            index=models.Index(fields=['codigo'], name='TIPO_PRESTA_codigo_da9103_idx'),
        ),
        migrations.AddIndex(
            model_name='tipoprestamo',
            index=models.Index(fields=['activo'], name='TIPO_PRESTA_activo_4bb6fe_idx'),
        ),
        migrations.AddConstraint(
            model_name='tipoprestamo',
            constraint=models.CheckConstraint(condition=models.Q(('tasa_interes_anual__gte', 0)), name='chk_tipo_prestamo_tasa_positiva'),
        ),
        migrations.AddConstraint(
            model_name='tipoprestamo',
            constraint=models.CheckConstraint(condition=models.Q(('plazo_minimo_meses__lte', models.F('plazo_maximo_meses'))), name='chk_tipo_prestamo_plazo_valido'),
        ),
        migrations.AddConstraint(
            model_name='tipoprestamo',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_garantes__gte', 0)), name='chk_tipo_prestamo_garantes_no_negativo'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo_prestamo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='banco.tipoprestamo'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='cuenta_ahorro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='banco.cuentaahorro'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='estado',
            field=models.ForeignKey(blank=True, limit_choices_to={'dominio': 'TRANSACCION'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='core.catestado'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='prestamo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones', to='banco.prestamo'),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='realizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transacciones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transaccion',
            name='transaccion_reversada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversos', to='banco.transaccion'),
        ),
        migrations.AddField(
            model_name='movimientofondomutuo',
            name='transaccion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movimientos_fondo', to='banco.transaccion'),
        ),
        migrations.AddIndex(
            model_name='fondomutuo',
            index=models.Index(fields=['periodo'], name='FONDO_MUTUO_periodo_416b72_idx'),
        ),
        migrations.AddIndex(
            model_name='fondomutuo',
            index=models.Index(fields=['estado'], name='FONDO_MUTUO_estado__26157d_idx'),
        ),
        migrations.AddIndex(
            model_name='fondomutuo',
            index=models.Index(fields=['-fecha_inicio'], name='FONDO_MUTUO_fecha_i_6fa5d5_idx'),
        ),
        migrations.AddConstraint(
            model_name='fondomutuo',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_disponible__gte', 0)), name='chk_fondo_saldo_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='fondomutuo',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='chk_fondo_fechas_validas'),
        ),
        migrations.AddConstraint(
            model_name='fondomutuo',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_disponible', django.db.models.expressions.CombinedExpression(models.F('total_ingresos'), '-', models.F('total_egresos')))), name='chk_fondo_saldo_correcto'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['socio', '-creado_en'], name='NOTIFICACIO_socio_i_6d4266_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['estado', 'programada_para'], name='NOTIFICACIO_estado__b8e512_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['enviado', 'programada_para'], name='NOTIFICACIO_enviado_b91f75_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['tipo', '-creado_en'], name='NOTIFICACIO_tipo_0badf9_idx'),
        ),
        migrations.AddIndex(
            model_name='notificacion',
            index=models.Index(fields=['-creado_en'], name='NOTIFICACIO_creado__622784_idx'),
        ),
        migrations.AddConstraint(
            model_name='notificacion',
            constraint=models.CheckConstraint(condition=models.Q(('intentos__gte', 0), ('intentos__lte', 10)), name='chk_notificacion_intentos_validos'),
        ),
        migrations.AddIndex(
            model_name='periododividendo',
            index=models.Index(fields=['año'], name='PERIODO_DIV_año_27e068_idx'),
        ),
        migrations.AddIndex(
            model_name='periododividendo',
            index=models.Index(fields=['estado'], name='PERIODO_DIV_estado_8c8017_idx'),
        ),
        migrations.AddConstraint(
            model_name='periododividendo',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gt', models.F('fecha_inicio'))), name='chk_periodo_fechas_validas'),
        ),
        migrations.AddConstraint(
            model_name='periododividendo',
            constraint=models.CheckConstraint(condition=models.Q(('total_distribuido__lte', models.F('total_intereses_generados'))), name='chk_periodo_distribucion_valida'),
        ),
        migrations.AddIndex(
            model_name='dividendo',
            index=models.Index(fields=['periodo', 'socio'], name='DIVIDENDO_periodo_e13208_idx'),
        ),
        migrations.AddIndex(
            model_name='dividendo',
            index=models.Index(fields=['acreditado'], name='DIVIDENDO_acredit_d4fd03_idx'),
        ),
        migrations.AddConstraint(
            model_name='dividendo',
            constraint=models.CheckConstraint(condition=models.Q(('monto_dividendo__gte', 0)), name='chk_dividendo_monto_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='dividendo',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad_prestamos__gte', 0)), name='chk_dividendo_prestamos_no_negativo'),
        ),
        migrations.AlterUniqueTogether(
            name='dividendo',
            unique_together={('periodo', 'socio')},
        ),
        migrations.AddIndex(
            model_name='pagoprestamo',
            index=models.Index(fields=['prestamo', '-fecha_pago'], name='PAGO_PRESTA_prestam_47bcd7_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoprestamo',
            index=models.Index(fields=['numero_recibo'], name='PAGO_PRESTA_numero__9a1132_idx'),
        ),
        migrations.AddIndex(
            model_name='pagoprestamo',
            index=models.Index(fields=['-fecha_pago'], name='PAGO_PRESTA_fecha_p_e65f32_idx'),
        ),
        migrations.AddConstraint(
            model_name='pagoprestamo',
            constraint=models.CheckConstraint(condition=models.Q(('monto_pagado__gt', 0)), name='chk_pago_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='pagoprestamo',
            constraint=models.CheckConstraint(condition=models.Q(('monto_capital__gte', 0), ('monto_interes__gte', 0), ('monto_mora__gte', 0)), name='chk_pago_componentes_no_negativos'),
        ),
        migrations.AddIndex(
            model_name='garante',
            index=models.Index(fields=['prestamo', 'activo'], name='GARANTE_prestam_f498b1_idx'),
        ),
        migrations.AddIndex(
            model_name='garante',
            index=models.Index(fields=['socio_garante', 'activo'], name='GARANTE_socio_g_19a3af_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='garante',
            unique_together={('prestamo', 'socio_garante')},
        ),
        migrations.AddIndex(
            model_name='cuotaprestamo',
            index=models.Index(fields=['prestamo', 'estado'], name='CUOTA_PREST_prestam_5c0747_idx'),
        ),
        migrations.AddIndex(
            model_name='cuotaprestamo',
            index=models.Index(fields=['estado', 'fecha_vencimiento'], name='CUOTA_PREST_estado_bd77f5_idx'),
        ),
        migrations.AddIndex(
            model_name='cuotaprestamo',
            index=models.Index(fields=['fecha_vencimiento'], name='CUOTA_PREST_fecha_v_a879e0_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuotaprestamo',
            constraint=models.CheckConstraint(condition=models.Q(('monto_cuota__gte', 0)), name='chk_cuota_monto_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cuotaprestamo',
            constraint=models.CheckConstraint(condition=models.Q(('dias_mora__gte', 0)), name='chk_cuota_dias_mora_no_negativo'),
        ),
        migrations.AlterUniqueTogether(
            name='cuotaprestamo',
            unique_together={('prestamo', 'numero_cuota')},
        ),
        migrations.AddIndex(
            model_name='solicitudayudamutua',
            index=models.Index(fields=['socio', '-fecha_solicitud'], name='SOLICITUD_A_socio_i_5d4cc6_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudayudamutua',
            index=models.Index(fields=['fondo', 'estado'], name='SOLICITUD_A_fondo_i_7f10e2_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudayudamutua',
            index=models.Index(fields=['estado', '-fecha_solicitud'], name='SOLICITUD_A_estado_047317_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudayudamutua',
            index=models.Index(fields=['numero_solicitud'], name='SOLICITUD_A_numero__ea24c0_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudayudamutua',
            index=models.Index(fields=['-fecha_solicitud'], name='SOLICITUD_A_fecha_s_08800a_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitudayudamutua',
            constraint=models.CheckConstraint(condition=models.Q(('monto_solicitado__gt', 0)), name='chk_solicitud_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='solicitudayudamutua',
            constraint=models.CheckConstraint(condition=models.Q(('monto_aprobado__isnull', True), ('monto_aprobado__gt', 0), _connector='OR'), name='chk_solicitud_monto_aprobado_positivo'),
        ),
        migrations.AddIndex(
            model_name='cuentaahorro',
            index=models.Index(fields=['socio', 'tipo_cuenta'], name='CUENTA_AHOR_socio_i_67c944_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaahorro',
            index=models.Index(fields=['numero_cuenta'], name='CUENTA_AHOR_numero__d5723f_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaahorro',
            index=models.Index(fields=['estado', 'fecha_cierre'], name='CUENTA_AHOR_estado__189252_idx'),
        ),
        migrations.AddIndex(
            model_name='cuentaahorro',
            index=models.Index(fields=['-creado_en'], name='CUENTA_AHOR_creado__d6bf52_idx'),
        ),
        migrations.AddConstraint(
            model_name='cuentaahorro',
            constraint=models.UniqueConstraint(condition=models.Q(('fecha_cierre__isnull', True)), fields=('socio', 'tipo_cuenta'), name='uq_cuenta_activa_por_tipo_socio'),
        ),
        migrations.AddConstraint(
            model_name='cuentaahorro',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_actual__gte', 0)), name='chk_cuenta_saldo_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='cuentaahorro',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_cierre__isnull', True), ('fecha_cierre__gte', models.F('fecha_apertura')), _connector='OR'), name='chk_cuenta_fecha_cierre_valida'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['socio', 'estado'], name='PRESTAMO_socio_i_7c1e13_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['numero_prestamo'], name='PRESTAMO_numero__89b932_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['estado', '-fecha_solicitud'], name='PRESTAMO_estado_7b54c3_idx'),
        ),
        migrations.AddIndex(
            model_name='prestamo',
            index=models.Index(fields=['-fecha_solicitud'], name='PRESTAMO_fecha_s_569831_idx'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.CheckConstraint(condition=models.Q(('monto_solicitado__gt', 0)), name='chk_prestamo_monto_solicitado_positivo'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.CheckConstraint(condition=models.Q(('monto_aprobado__isnull', True), ('monto_aprobado__gt', 0), _connector='OR'), name='chk_prestamo_monto_aprobado_positivo'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.CheckConstraint(condition=models.Q(('plazo_meses__gte', 1)), name='chk_prestamo_plazo_minimo'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_pendiente__gte', 0)), name='chk_prestamo_saldo_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='prestamo',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_aprobacion__isnull', True), ('fecha_aprobacion__gte', models.F('fecha_solicitud')), _connector='OR'), name='chk_prestamo_fecha_aprobacion_valida'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['cuenta_ahorro', '-fecha_transaccion'], name='TRANSACCION_cuenta__31bc33_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['prestamo', '-fecha_transaccion'], name='TRANSACCION_prestam_0f1de9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['tipo_transaccion', '-fecha_transaccion'], name='TRANSACCION_tipo_tr_5847ce_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['estado', '-fecha_transaccion'], name='TRANSACCION_estado__cb4c4d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['numero_recibo'], name='TRANSACCION_numero__0357f2_idx'),
        ),
        migrations.AddIndex(
            model_name='transaccion',
            index=models.Index(fields=['-fecha_transaccion'], name='TRANSACCION_fecha_t_222a1a_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaccion',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('cuenta_ahorro__isnull', False), ('prestamo__isnull', True)), models.Q(('cuenta_ahorro__isnull', True), ('prestamo__isnull', False)), _connector='OR'), name='chk_transaccion_origen_xor'),
        ),
        migrations.AddConstraint(
            model_name='transaccion',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='chk_transaccion_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='transaccion',
            constraint=models.CheckConstraint(condition=models.Q(('cuenta_ahorro__isnull', True), ('saldo_nuevo__gte', 0), _connector='OR'), name='chk_transaccion_saldo_no_negativo'),
        ),
        migrations.AddIndex(
            model_name='movimientofondomutuo',
            index=models.Index(fields=['fondo', '-fecha_movimiento'], name='MOVIMIENTO__fondo_i_6ff759_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofondomutuo',
            index=models.Index(fields=['socio', '-fecha_movimiento'], name='MOVIMIENTO__socio_i_004659_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofondomutuo',
            index=models.Index(fields=['origen', '-fecha_movimiento'], name='MOVIMIENTO__origen_4a4467_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofondomutuo',
            index=models.Index(fields=['numero_movimiento'], name='MOVIMIENTO__numero__0f6918_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientofondomutuo',
            index=models.Index(fields=['-fecha_movimiento'], name='MOVIMIENTO__fecha_m_7fd981_idx'),
        ),
        migrations.AddConstraint(
            model_name='movimientofondomutuo',
            constraint=models.CheckConstraint(condition=models.Q(('monto__gt', 0)), name='chk_movimiento_monto_positivo'),
        ),
        migrations.AddConstraint(
            model_name='movimientofondomutuo',
            constraint=models.CheckConstraint(condition=models.Q(('saldo_anterior__gte', 0), ('saldo_nuevo__gte', 0)), name='chk_movimiento_saldos_no_negativos'),
        ),
    ]
